### ISSUE TITLE
Output to stderr

### ISSUE THREAD

**Issue by Cxarli** [redstarcoder/go-starfish#3]
First of all, cool language, I'm trying to use it for a fun project.

However, for some reason,

```
"Hello, World!" r`;
              l?!`o
```

outputs "Hello, World!" to stderr, instead of to stdout.

**Comment by redstarcoder** [comment]
Wow I'm glad you're interested in *><>! I've looked into your issue and you're correct, it outputs to stderr (ugh!).

This is because I use `print` and `println`, [unaware they output to stderr](https://golang.org/pkg/builtin/#print). The code causing you grief is here: https://github.com/redstarcoder/go-starfish/blob/master/starfish/starfish.go#L312 (`print(string(byte(cB.Pop())))`)

I'll try to fix it immediately!

**Comment by Cxarli** [comment]
Thanks! :+1:
